[package]
name = "contender"
version = "0.1.0"
edition = "2021"
authors = ["Brock Smedley"]

[lib]
name = "contender_core"
path = "src/lib.rs"

[[bin]]
name = "contender_cli"
path = "src/bin/cli.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
sqlite = "0.36.1"
