[package]
name = "contender_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "contender"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
serde = { workspace = true }
contender_core = { workspace = true }
contender_sqlite = { workspace = true }
contender_testfile = { workspace = true }

clap = { workspace = true, features = ["derive"] }
alloy = { workspace = true, features = ["full", "node-bindings"] }
csv = { workspace = true }
