[package]
name = "contender_testfile"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = {workspace = true}
alloy = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
contender_core = { workspace = true }
